title: pjocke.cloud ☁️
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
show_downloads: false
is_user_page: true
is_project_page: false
default:
  - scope:
      path:
      type: posts
    values:
      author_profile: true
author:
  name: "Joakim Bomelin
  bio: "Noot, noot!"
  location: "Malmö, Sweden"

