title: pjocke.cloud ☁️
author:
  name: "pjocke"
  bio: "Noot, noot!"
  location: "Malmo, Sweden"
theme: minima
show_excerpts: true
show_downloads: false
is_user_page: true
is_project_page: false
defaults:
  - scope:
      path: "/_posts"
      type: posts
    values:
      author_profile: true
