title: pjocke.cloud ☁️
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: false
is_user_page: true
is_project_page: false
defaults:
  - scope:
      path: "/_posts"
      type: posts
    values:
      author_profile: true
author:
  name: "pjocke"
  bio: "Noot, noot!"
  location: "Malmo, Sweden"
